import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const SummaryCard = ({ title, value, icon, color, trend, subtext, }) => {
    return (_jsx("div", { className: `${color} rounded-lg p-6 shadow-lg hover:shadow-xl transition-shadow`, children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium opacity-90", children: title }), _jsx("p", { className: "text-3xl font-bold mt-2", children: value.toLocaleString() }), trend !== undefined && (_jsxs("p", { className: `text-xs mt-2 ${trend >= 0 ? 'text-red-200' : 'text-green-200'}`, children: [trend >= 0 ? '↑' : '↓', " ", Math.abs(trend), "% from last hour"] })), subtext && _jsx("p", { className: "text-xs mt-1 opacity-75", children: subtext })] }), _jsx("div", { className: "text-4xl opacity-20", children: icon })] }) }));
};
export const ThreatSummary = ({ stats }) => {
    return (_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4 mb-8", children: [_jsx(SummaryCard, { title: "Total Alerts", value: stats.total_alerts, icon: "\uD83D\uDEA8", color: "bg-gradient-to-br from-blue-600 to-blue-800 text-white", trend: 5 }), _jsx(SummaryCard, { title: "Critical", value: stats.critical_alerts, icon: "\u26A0\uFE0F", color: "bg-gradient-to-br from-red-600 to-red-800 text-white", trend: 12 }), _jsx(SummaryCard, { title: "High", value: stats.high_alerts, icon: "\uD83D\uDD34", color: "bg-gradient-to-br from-orange-600 to-orange-800 text-white", trend: 8 }), _jsx(SummaryCard, { title: "Medium", value: stats.medium_alerts, icon: "\uD83D\uDFE1", color: "bg-gradient-to-br from-yellow-600 to-yellow-800 text-white", trend: -3 }), _jsx(SummaryCard, { title: "Low", value: stats.low_alerts, icon: "\uD83D\uDFE2", color: "bg-gradient-to-br from-green-600 to-green-800 text-white", trend: -5 })] }));
};
export const LiveMetrics = ({ packets_per_sec, bytes_per_sec, active_threats, }) => {
    return (_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4 mb-8", children: [_jsxs("div", { className: "bg-gradient-to-br from-purple-500 to-purple-700 text-white rounded-lg p-6 shadow-lg", children: [_jsx("p", { className: "text-sm font-medium opacity-90", children: "Packets/sec" }), _jsx("p", { className: "text-3xl font-bold mt-2", children: packets_per_sec.toLocaleString() }), _jsx("div", { className: "mt-4 h-1 bg-purple-300 rounded-full overflow-hidden", children: _jsx("div", { className: "h-full bg-purple-100 animate-pulse", style: {
                                width: `${Math.min((packets_per_sec / 100000) * 100, 100)}%`,
                                animation: 'pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                            } }) })] }), _jsxs("div", { className: "bg-gradient-to-br from-indigo-500 to-indigo-700 text-white rounded-lg p-6 shadow-lg", children: [_jsx("p", { className: "text-sm font-medium opacity-90", children: "Bytes/sec" }), _jsxs("p", { className: "text-3xl font-bold mt-2", children: [(bytes_per_sec / 1024 / 1024).toFixed(2), " MB/s"] }), _jsx("p", { className: "text-xs mt-4 opacity-75", children: "Network throughput" })] }), _jsxs("div", { className: "bg-gradient-to-br from-cyan-500 to-cyan-700 text-white rounded-lg p-6 shadow-lg", children: [_jsx("p", { className: "text-sm font-medium opacity-90", children: "Active Threats" }), _jsx("p", { className: "text-3xl font-bold mt-2", children: active_threats }), _jsx("p", { className: "text-xs mt-4 opacity-75", children: "Currently monitoring" })] })] }));
};
export const RecentAlertsTable = ({ alerts, onAlertClick, loading = false, }) => {
    const getSeverityColor = (severity) => {
        switch (severity) {
            case 'CRITICAL':
                return 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200';
            case 'HIGH':
                return 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200';
            case 'MEDIUM':
                return 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200';
            case 'LOW':
                return 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200';
            default:
                return 'bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-200';
        }
    };
    if (loading) {
        return (_jsx("div", { className: "bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6", children: _jsx("div", { className: "flex justify-center", children: _jsx("div", { className: "animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500" }) }) }));
    }
    return (_jsxs("div", { className: "bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden", children: [_jsx("div", { className: "px-6 py-4 bg-gray-50 dark:bg-gray-700 border-b border-gray-200 dark:border-gray-600", children: _jsx("h3", { className: "text-lg font-semibold text-gray-900 dark:text-white", children: "Recent Alerts" }) }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { className: "bg-gray-100 dark:bg-gray-700 border-b border-gray-200 dark:border-gray-600", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-3 text-left text-sm font-medium text-gray-700 dark:text-gray-300", children: "Timestamp" }), _jsx("th", { className: "px-6 py-3 text-left text-sm font-medium text-gray-700 dark:text-gray-300", children: "Source IP" }), _jsx("th", { className: "px-6 py-3 text-left text-sm font-medium text-gray-700 dark:text-gray-300", children: "Threat Type" }), _jsx("th", { className: "px-6 py-3 text-left text-sm font-medium text-gray-700 dark:text-gray-300", children: "Severity" }), _jsx("th", { className: "px-6 py-3 text-left text-sm font-medium text-gray-700 dark:text-gray-300", children: "Protocol" })] }) }), _jsx("tbody", { className: "divide-y divide-gray-200 dark:divide-gray-700", children: alerts.length === 0 ? (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "px-6 py-4 text-center text-gray-500 dark:text-gray-400", children: "No alerts yet" }) })) : (alerts.map((alert) => (_jsxs("tr", { onClick: () => onAlertClick(alert), className: "hover:bg-gray-50 dark:hover:bg-gray-700 cursor-pointer transition-colors", children: [_jsx("td", { className: "px-6 py-4 text-sm text-gray-900 dark:text-gray-300", children: new Date(alert.timestamp).toLocaleString() }), _jsx("td", { className: "px-6 py-4 text-sm font-mono text-gray-900 dark:text-gray-300", children: alert.src_ip }), _jsx("td", { className: "px-6 py-4 text-sm text-gray-900 dark:text-gray-300", children: alert.threat_type }), _jsx("td", { className: "px-6 py-4 text-sm", children: _jsx("span", { className: `px-3 py-1 rounded-full text-xs font-semibold ${getSeverityColor(alert.severity)}`, children: alert.severity }) }), _jsx("td", { className: "px-6 py-4 text-sm font-mono text-gray-900 dark:text-gray-300", children: alert.protocol.toUpperCase() })] }, alert.id)))) })] }) })] }));
};
//# sourceMappingURL=Cards.js.map