import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const SummaryCard = ({ title, value, icon, color, trend, subtext, }) => {
    return (_jsx("div", { className: `${color} rounded-lg p-6 shadow-lg hover:shadow-xl transition-shadow`, children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-slate-200", children: title }), _jsx("p", { className: "text-3xl font-bold mt-2 text-slate-50", children: value.toLocaleString() }), trend !== undefined && (_jsxs("p", { className: `text-xs mt-2 ${trend >= 0 ? 'text-pink-300' : 'text-green-300'}`, children: [trend >= 0 ? '↑' : '↓', " ", Math.abs(trend), "% from last hour"] })), subtext && _jsx("p", { className: "text-xs mt-1 text-slate-300", children: subtext })] }), _jsx("div", { className: "text-4xl opacity-30", children: icon })] }) }));
};
export const ThreatSummary = ({ stats }) => {
    return (_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4 mb-8", children: [_jsx(SummaryCard, { title: "Total Alerts", value: stats.total_alerts, icon: "\uD83D\uDEA8", color: "bg-gradient-to-br from-slate-700 to-slate-900 text-white", trend: 5 }), _jsx(SummaryCard, { title: "Critical", value: stats.critical_alerts, icon: "\u26A0\uFE0F", color: "bg-gradient-to-br from-red-900 to-red-950 text-white", trend: 12 }), _jsx(SummaryCard, { title: "High", value: stats.high_alerts, icon: "\uD83D\uDD34", color: "bg-gradient-to-br from-orange-900 to-orange-950 text-white", trend: 8 }), _jsx(SummaryCard, { title: "Medium", value: stats.medium_alerts, icon: "\uD83D\uDFE1", color: "bg-gradient-to-br from-yellow-900 to-yellow-950 text-white", trend: -3 }), _jsx(SummaryCard, { title: "Low", value: stats.low_alerts, icon: "\uD83D\uDFE2", color: "bg-gradient-to-br from-green-900 to-green-950 text-white", trend: -5 })] }));
};
export const LiveMetrics = ({ packets_per_sec, bytes_per_sec, active_threats, }) => {
    return (_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4 mb-8", children: [_jsxs("div", { className: "bg-gradient-to-br from-slate-700 to-slate-900 text-white rounded-lg p-6 shadow-lg", children: [_jsx("p", { className: "text-sm font-medium text-slate-200", children: "Packets/sec" }), _jsx("p", { className: "text-3xl font-bold mt-2 text-slate-50", children: packets_per_sec.toLocaleString() }), _jsx("div", { className: "mt-4 h-1 bg-slate-600 rounded-full overflow-hidden", children: _jsx("div", { className: "h-full bg-cyan-400 animate-pulse", style: {
                                width: `${Math.min((packets_per_sec / 100000) * 100, 100)}%`,
                                animation: 'pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                            } }) })] }), _jsxs("div", { className: "bg-gradient-to-br from-slate-700 to-slate-900 text-white rounded-lg p-6 shadow-lg", children: [_jsx("p", { className: "text-sm font-medium text-slate-200", children: "Bytes/sec" }), _jsxs("p", { className: "text-3xl font-bold mt-2 text-slate-50", children: [(bytes_per_sec / 1024 / 1024).toFixed(2), " MB/s"] }), _jsx("p", { className: "text-xs mt-4 text-slate-400", children: "Network throughput" })] }), _jsxs("div", { className: "bg-gradient-to-br from-slate-700 to-slate-900 text-white rounded-lg p-6 shadow-lg", children: [_jsx("p", { className: "text-sm font-medium text-slate-200", children: "Active Threats" }), _jsx("p", { className: "text-3xl font-bold mt-2 text-slate-50", children: active_threats }), _jsx("p", { className: "text-xs mt-4 text-slate-400", children: "Currently monitoring" })] })] }));
};
export const RecentAlertsTable = ({ alerts, onAlertClick, loading = false, }) => {
    const getSeverityColor = (severity) => {
        switch (severity) {
            case 'CRITICAL':
                return 'bg-red-900 text-red-100 dark:bg-red-900 dark:text-red-100';
            case 'HIGH':
                return 'bg-orange-900 text-orange-100 dark:bg-orange-900 dark:text-orange-100';
            case 'MEDIUM':
                return 'bg-yellow-900 text-yellow-100 dark:bg-yellow-900 dark:text-yellow-100';
            case 'LOW':
                return 'bg-green-900 text-green-100 dark:bg-green-900 dark:text-green-100';
            default:
                return 'bg-slate-700 text-slate-200 dark:bg-slate-700 dark:text-slate-200';
        }
    };
    if (loading) {
        return (_jsx("div", { className: "bg-slate-800 dark:bg-slate-800 rounded-lg shadow-lg p-6", children: _jsx("div", { className: "flex justify-center", children: _jsx("div", { className: "animate-spin rounded-full h-8 w-8 border-b-2 border-cyan-500" }) }) }));
    }
    return (_jsxs("div", { className: "bg-slate-800 dark:bg-slate-800 rounded-lg shadow-lg overflow-hidden", children: [_jsx("div", { className: "px-6 py-4 bg-slate-700 dark:bg-slate-700 border-b border-slate-600 dark:border-slate-600", children: _jsx("h3", { className: "text-lg font-semibold text-slate-100 dark:text-slate-100", children: "Recent Alerts" }) }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { className: "bg-slate-700 dark:bg-slate-700 border-b border-slate-600 dark:border-slate-600", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-3 text-left text-sm font-medium text-slate-300 dark:text-slate-300", children: "Timestamp" }), _jsx("th", { className: "px-6 py-3 text-left text-sm font-medium text-slate-300 dark:text-slate-300", children: "Source IP" }), _jsx("th", { className: "px-6 py-3 text-left text-sm font-medium text-slate-300 dark:text-slate-300", children: "Threat Type" }), _jsx("th", { className: "px-6 py-3 text-left text-sm font-medium text-slate-300 dark:text-slate-300", children: "Severity" }), _jsx("th", { className: "px-6 py-3 text-left text-sm font-medium text-slate-300 dark:text-slate-300", children: "Protocol" })] }) }), _jsx("tbody", { className: "divide-y divide-slate-700 dark:divide-slate-700", children: alerts.length === 0 ? (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "px-6 py-4 text-center text-slate-400 dark:text-slate-400", children: "No alerts yet" }) })) : (alerts.map((alert) => (_jsxs("tr", { onClick: () => onAlertClick(alert), className: "hover:bg-slate-700 dark:hover:bg-slate-700 cursor-pointer transition-colors", children: [_jsx("td", { className: "px-6 py-4 text-sm text-slate-300 dark:text-slate-300", children: new Date(alert.timestamp).toLocaleString() }), _jsx("td", { className: "px-6 py-4 text-sm font-mono text-slate-300 dark:text-slate-300", children: alert.src_ip }), _jsx("td", { className: "px-6 py-4 text-sm text-slate-300 dark:text-slate-300", children: alert.threat_type }), _jsx("td", { className: "px-6 py-4 text-sm", children: _jsx("span", { className: `px-3 py-1 rounded-full text-xs font-semibold ${getSeverityColor(alert.severity)}`, children: alert.severity }) }), _jsx("td", { className: "px-6 py-4 text-sm font-mono text-slate-300 dark:text-slate-300", children: alert.protocol.toUpperCase() })] }, alert.id)))) })] }) })] }));
};
//# sourceMappingURL=Cards.js.map